apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: admin-server
  name: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin-server
  template:
    metadata:
      labels:
        io.kompose.service: admin-server
    spec:
      containers:
        - command:
            - ./dockerize
            - -wait=tcp://discovery-server:8761
            - -timeout=60s
            - --
            - java
            - org.springframework.boot.loader.JarLauncher
          image: asia-northeast3-docker.pkg.dev/hyunyoung-01-368306/gcpzg/spring-petclinic-admin-server
          name: admin-server
          ports:
            - containerPort: 9090
      restartPolicy: Always
