apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-server
  template:
    metadata:
      labels:
        io.kompose.service: config-server
    spec:
      containers:
        - image: asia-northeast3-docker.pkg.dev/hyunyoung-01-368306/gcpzg/spring-petclinic-config-server
          name: config-server
          ports:
            - containerPort: 8888
      restartPolicy: Always
