apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: discovery-server
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery-server
  template:
    metadata:
      labels:
        io.kompose.service: discovery-server
    spec:
      containers:
        - command:
            - ./dockerize
            - -wait=tcp://config-server:8888
            - -timeout=60s
            - --
            - java
            - org.springframework.boot.loader.JarLauncher
          image: asia-northeast3-docker.pkg.dev/hyunyoung-01-368306/gcpzg/spring-petclinic-discovery-server
          name: discovery-server
          ports:
            - containerPort: 8761
      restartPolicy: Always
