#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  labels:
#    io.kompose.service: prometheus-server
#  name: prometheus-server
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      io.kompose.service: prometheus-server
#  template:
#    metadata:
#      labels:
#        io.kompose.service: prometheus-server
#    spec:
#      containers:
#        - image: prometheus-server
#          name: prometheus-server
#          ports:
#            - containerPort: 9090
#      restartPolicy: Always
